print("What is your name?")
student=input()
print(student + ' ' + "can't wait to start writing harder programs!")
print("Who is your favorite instructor?")
instructor = input()
print("My favorite instructor is " + instructor +' '+ "and he is AWESOME.")
print("Which team are you on?")
team = input()
print(team +' '+ "is the best team in all of MEET")
